---

- name: Ensure hostname is set to inventory hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Ensure ubuntu 127.0.1.1 loopback is absent
  lineinfile:
    regexp: "^127\\.0\\.1\\.1\\s+.*"
    state: absent
    dest: "/etc/hosts"

- name: Ensure 127.0.0.1 loopback resolve to hostname doesnt exist
  lineinfile:
    regexp: "^127\\.0\\.0\\.1\\s+{{ inventory_hostname }}.*"
    state: absent
    dest: "/etc/hosts"

- name: Ensure ubuntu 127.0.0.1 loopback only contains localhost
  lineinfile:
    line: "127.0.0.1 localhost"
    regexp: "^127\\.0\\.0\\.1\\s+localhost$"
    dest: "/etc/hosts"

- name: Ensure /etc/hosts file has all host entries from specified group
  when: hostvars[item][hostsfile_iface]['ipv4']['address'] is defined
  lineinfile:
    line: "{{ hostvars[item][hostsfile_iface]['ipv4']['address'] }} {{ item }}"
    state: present
    dest: "/etc/hosts"
  with_items: "{{ groups[hostsfile_group] }}"
