---

kafka_version: "0.11.0.0"
kafka_scala_version: "2.11"

kafka_user: "kafka"
kafka_group: "kafka"

kafka_package_install_method: "download"

kafka_download_name: "kafka_{{ kafka_scala_version }}-{{ kafka_version }}"
kafka_download_ext: "tgz"
kafka_download_url: "http://mirrors.sonic.net/apache/kafka/{{ kafka_version }}/{{ kafka_download_name }}.{{ kafka_download_ext }}"

kafka_download_dest_parent_dir: "/var/tmp"

kafka_parent_dir: "/opt"
kafka_dir: "{{ kafka_parent_dir }}/{{ kafka_download_name }}"

kafka_symlink: "/opt/kafka"

# server properties
kafka_brokers:
  - localhost
#kafka_listener_host: "{{ inventory_hostname }}"
kafka_listeners_port: "9092"
kafka_log_dirs: "{{ kafka_dir }}/logs"
kafka_zk_endpoint: "localhost:2181"

#connect-standalone.properties
kafka_bootstrap_servers: "localhost:9092"
