---

- name: Ensure Apache present
  apt:
    name: apache2
    cache_valid_time: 3600
    update_cache: yes

- name: Ensure dirs exist
  file:
    dest: "{{ schema_registry_ui_parentdir }}"
    state: directory
    owner: "{{ schema_registry_ui_owner }}"
    group: "{{ schema_registry_ui_group }}"
    mode: "0755"
    recurse: yes

- name: Ensure Schema Registry UI downloaded
  when: schema_registry_ui_download == "url"
  get_url:
    url: "{{ schema_registry_ui_tarball_url }}"
    dest: "{{ schema_registry_ui_tarball_dest }}"

- name: Ensure Schema Registry UI tarball copied to node - {{ schema_registry_ui_tarball_dest }}
  when: schema_registry_ui_download != "url"
  copy:
    src: "{{ schema_registry_ui_tarball_file }}"
    dest: "{{ schema_registry_ui_tarball_dest }}"

- name: Ensure {{ schema_registry_ui_tarball_dest }} is unarchived to {{ schema_registry_ui_parentdir }}/{{ schema_registry_ui_tarball_name }}
  unarchive:
    src: "{{ schema_registry_ui_tarball_dest }}"
    dest: "{{ schema_registry_ui_parentdir }}"
    owner: "{{ schema_registry_ui_owner }}"
    group: "{{ schema_registry_ui_group }}"
    mode: "0755"
    remote_src: yes
    creates: "{{ schema_registry_ui_parentdir }}/index.html"

- name: Template env.js
  template:
    src: env.js
    dest: "{{ schema_registry_ui_parentdir }}/env.js"
    owner: "{{ schema_registry_ui_owner }}"
    group: "{{ schema_registry_ui_group }}"
    mode: "0755"

- name: Ensure Vhost copied to Apache dir
  template:
    src: schema_registry_ui.conf
    dest: /etc/apache2/sites-available/schema_registry_ui.conf
    owner: "{{ schema_registry_ui_owner }}"
    group: "{{ schema_registry_ui_group }}"

- name: Ensure default vhost disabled
  shell: a2dissite 000-default
  register: a2dissite_default
  failed_when: >
    a2dissite_default.rc != 0 and ("does not exist!" not in a2dissite_default.stderr)
  changed_when: False

- name: Ensure schema_registry_ui.conf enabled in Apache
  shell: a2ensite schema_registry_ui
  register: a2ensite_schema_registry_ui
  failed_when: >
    a2ensite_schema_registry_ui.rc != 0 and ("already enabled" not in a2ensite_schema_registry_ui.stderr)
  changed_when: False

- name: Ensure virtualhost port {{ schema_registry_port }} listening in apache2
  register: schema_registry_port
  lineinfile:
    dest: "/etc/apache2/ports.conf"
    line: "Listen {{ schema_registry_port }}"
    regexp: "^Listen\\s{{ schema_registry_port }}\\s*$"

- name: Reload Apache
  when: schema_registry_port|changed or a2dissite_default|changed
  service:
    name: apache2
    state: reloaded
