---

- name: Ensure systemd service in desired state
  systemd:
    name: "{{ item.name }}"
    state: "{{ item.state|default('started') }}"
    daemon_reload: yes
  with_items: "{{ confluent_services }}"
