---

# Kafka specific hosts

data_nodes:
  hosts:
    - data1.lan
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"

confluent_servers:
  children:
    - data_nodes

# Khermes Akka App specific hosts

akka_seeds:
  hosts:
    - akka1.lan
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"

akka_nodes:
  hosts:
    - akka1.lan
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"

akka_cluster:
  children:
    - akka_seeds
    - akka_nodes

# Host Specific

_meta:
  hostvars:
    data1.lan:
      vagrant_mem: 8192
      vagrant_disks:
        - size: 10000
